import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Loader } from "@/components/ui/loader";
import axiosInstance from "@/lib/axios";
import { formatAllResponses } from "@/lib/utils";
import type { AiResponse, Prediction, PredictionRequest } from "@/types";
import { Droplets, Leaf, Lightbulb, Thermometer } from "lucide-react";
import { Activity, useEffect, useState } from "react";

type props = {
  requestData: PredictionRequest;
  responseData: Prediction;
};

const AiSuggestionCard = ({ requestData, responseData }: props) => {
  const [isLoading, setIsLoading] = useState(true);
  const [aiSuggestions, setAiSuggestions] = useState<AiResponse | null>(null);

  useEffect(() => {
    let isMounted = true;

    const fetchSuggestions = async () => {
      if (!requestData || !responseData) {
        setIsLoading(false);
        return;
      }

      setIsLoading(true);

      try {
        const res = await axiosInstance.post("predict/ai-suggestion", {
          requestData,
          responseData,
        });

        if (isMounted) {
          setAiSuggestions(res.data as AiResponse);
        }
      } catch (error) {
        console.error("Error fetching AI suggestions:", error);
        if (isMounted) {
          setAiSuggestions(null);
        }
      } finally {
        if (isMounted) {
          setIsLoading(false);
        }
      }
    };

    fetchSuggestions();

    return () => {
      isMounted = false;
    };
  }, [requestData, responseData]);

  const getIcon = (title: string) => {
    const iconMap: Record<string, any> = {
      "Optimal Irrigation Strategy": Droplets,
      "Soil Health Management": Leaf,
      "Temperature & Climate Adaptation": Thermometer,
      "Nutrient Management Plan": Lightbulb,
    };

    return iconMap[title] ?? Lightbulb;
  };

  if (!requestData || !responseData) return <div>Something went wrong</div>;
  if (isLoading)
    return (
      <div className="h-48 w-full flex items-center justify-center">
        <Loader size="lg" text="Generating AI recommendations..." />
      </div>
    );

  console.log({ aiSuggestions });
  return (
    <Activity mode={isLoading ? "hidden" : "visible"}>
      <Card className="border-border">
        <CardHeader>
          <CardTitle className="text-card-foreground flex items-center gap-2">
            <Lightbulb className="h-5 w-5 text-accent" />
            AI-Powered Recommendations
          </CardTitle>
          <CardDescription>
            Smart insights based on your field conditions and predicted yield
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {formatAllResponses(aiSuggestions!).map((suggestion, index) => {
              const Icon = getIcon(suggestion.title);
              return (
                <div
                  key={index}
                  className="p-5 rounded-xl bg-muted border-border"
                >
                  <div className="flex items-start gap-3">
                    <div className="size-10 rounded-lg flex items-center justify-center shrink-0 bg-primary/10">
                      <Icon className="h-5 w-5 text-primary" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-2">
                        <h4 className="font-semibold text-card-foreground">
                          {suggestion.title}
                        </h4>
                      </div>
                      <p className="text-sm text-muted-foreground leading-relaxed">
                        {suggestion.description}
                      </p>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>

          <div className="mt-6 p-4 rounded-xl bg-chart-3/10 border border-chart-3/20">
            <p className="text-sm text-card-foreground">
              <span className="font-semibold">💡 Pro Tip:</span> These
              recommendations are generated by AI model using NASA POWER weather
              data and SoilGrids soil analysis. For best results, monitor your
              field conditions regularly and adjust practices as needed.
            </p>
          </div>
        </CardContent>
      </Card>
    </Activity>
  );
};

export default AiSuggestionCard;
