spring:
  application:
    name: SBS_HackTheGap
    # noinspection SpellCheckingInspection
    secret-key: ${SECRET_KEY:sssssssssssssssssssssssssssssssssssssssssssssssssssssss}
    frontend-urls: http://localhost:3000, http://localhost:5173
    ml-service-url: http://localhost:8000
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  datasource:
    url: jdbc:postgresql://localhost:5432/sbs
    username: meet
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  ai:
    azure:
      openai:
        api-key: ${AZURE_OPENAI_API_KEY}
        endpoint: ${AZURE_OPENAI_ENDPOINT}
        chat:
          options:
            deployment-name: o4-mini
            temperature: 1
