spring:
  application:
    name: SBS_HackTheGap
  datasource:
    url: jdbc:postgresql://localhost:5432/sbs
    username: meet
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


