spring:
  application:
    name: SBS_HackTheGap
    # noinspection SpellCheckingInspection
    secret-key: ${SECRET_KEY:sssssssssssssssssssssssssssssssssssssssssssssssssssssss}
    frontend-urls: http://localhost:3000, http://localhost:5731
  datasource:
    url: jdbc:postgresql://localhost:5432/sbs
    username: meet
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


