---
- name: Deploy SBS Hackathon demo
  become: true
  hosts: Name_SBS_HackTheGap_2026
  vars:
    project_path: "{{ ansible_env.HOME }}/SBS_HackTheGap_2026"
    AZURE_OPENAI_API_KEY: "{{ lookup('env', 'AZURE_OPENAI_API_KEY') }}"
    AZURE_OPENAI_ENDPOINT: "{{ lookup('env', 'AZURE_OPENAI_ENDPOINT') }}"
    SECRET_KEY: "{{ lookup('env', 'SECRET_KEY') }}"
    GOOGLE_CLIENT_ID: "{{ lookup('env', 'GOOGLE_CLIENT_ID') }}"
    GOOGLE_CLIENT_SECRET: "{{ lookup('env', 'GOOGLE_CLIENT_SECRET') }}"
    FACEBOOK_CLIENT_ID: "{{ lookup('env', 'FACEBOOK_CLIENT_ID') }}"
    FACEBOOK_CLIENT_SECRET: "{{ lookup('env', 'FACEBOOK_CLIENT_SECRET') }}"

  pre_tasks:
    - name: Ensure project directory exists
      ansible.builtin.file:
        path: "{{ project_path }}"
        state: directory

  roles:
    - docker_install
    - create_env
    - certbot_ssl

  tasks:
    - name: Copy docker-compose
      copy:
        src: "../docker-compose.yml"
        dest: "{{ project_path }}/docker-compose.yml"

    - name: Deploy application
      community.docker.docker_compose_v2:
        project_src: "{{ project_path }}"
        state: present
        pull: always
        recreate: auto
